backend:
  name: github
  repo: spasiblya/spasiblya
  branch: main
  auth_type: oauth
  base_url: https://spasiblya.netlify.app
  auth_endpoint: api/auth

media_folder: "img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Статьи"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }





